Homework 07
Yevhenko/ma-nodejs-2020 pull request #11
Opened 2020-01-17 15:17 UTC by Yevhenko

2020-01-18 23:27 UTC, VitaliiHurin requested changes

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/controller.js
> +        if (filter === 'total') {
Оцей if з includes не потрібен якщо нижче знов ті самі перевірки ідуть через окремі if'и.

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/controller.js
> +    if (authorization !== 'Basic WWV2aGVuOjEyMzQ1') {
Погана практика так відкрито тримати пароль і перевіряти його звичайним способом, але зараз в рамках даного завдання це не дуже критично...

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/router.js
> +    default:
Для default теж можна 404 віддавати.

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/controller.js
> +const result8 = {
Всі оці значення з HW() тут дістануться лише один раз і потім завжди будуть статичні при всіх інших  запитах.
Також краще нормально називати змінні, а не так неочевидно result1, result2 і т.д.

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/router.js
> +      if (url.pathname === '/limit' && method === 'POST') controller.getLimit(req, res);
Чому getLimit якщо метод POST? :)
Також тут не треба в if'і ще раз перевіряти pathname.

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/controller.js
> +async function getMetricsWithFilter(req, res) {
Тут нема перевірки авторизації на відміну від інших. :(

2020-01-18 23:27 UTC, VitaliiHurin commented on homework-07/src/controller.js
> +    res.end(JSON.stringify(result, (result.message = 'OK')));
Що тут робить другий параметр в JSON.stringify?

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/controller.js
> +        if (filter === 'total') {
fixed

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/controller.js
> +    if (authorization !== 'Basic WWV2aGVuOjEyMzQ1') {
fixed

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/router.js
> +    default:
fixed

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/controller.js
> +const result8 = {
fixed

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/router.js
> +      if (url.pathname === '/limit' && method === 'POST') controller.getLimit(req, res);
fixed

2020-01-19 14:55 UTC, Yevhenko commented on homework-07/src/controller.js
> +async function getMetricsWithFilter(req, res) {
fixed

2020-01-19 14:56 UTC, Yevhenko commented on homework-07/src/controller.js
> +    res.end(JSON.stringify(result, (result.message = 'OK')));
fixed

2020-01-26 18:28 UTC, RPVanarx approved these changes

2020-01-27 22:26 UTC, VitaliiHurin approved these changes

2020-01-27 23:02 UTC, merged