homework-04 committed
Yevhenko/ma-nodejs-2020 pull request #7
Opened 2019-12-06 17:07 UTC by Yevhenko

2019-12-08 19:27 UTC, VitaliiHurin commented
Чому там всі файли попередніх домашок, а не тільки homework-04?

2019-12-08 19:30 UTC, VitaliiHurin requested changes

2019-12-08 19:30 UTC, VitaliiHurin commented on homework-04/package.json
> +  "name": "homework-01",
Ім'я не те. :)
Файл старий.

2019-12-08 19:30 UTC, VitaliiHurin commented on homework-04/package.json
> +    "nanoid": "^2.1.6"
Не використовується.

2019-12-08 19:30 UTC, VitaliiHurin commented on homework-04/src/02.js
> +}, 700);
Майже як на колбеках. :)
Можна зробити на промісах без таких вкладеностей глибоких.

2019-12-10 19:43 UTC, Yevhenko commented on homework-04/src/02.js
> +}, 700);
спробував переробити

2019-12-10 19:43 UTC, Yevhenko commented on homework-04/src/02.js
> +}, 700);
спробував переробити

2019-12-10 19:45 UTC, Yevhenko commented on homework-04/src/02.js
> +}, 700);
спробував переробити

2019-12-15 18:40 UTC, VitaliiHurin approved these changes

2019-12-15 18:41 UTC, RPVanarx approved these changes

2019-12-16 11:34 UTC, merged