Homework 05
Yevhenko/ma-nodejs-2020 pull request #8
Opened 2019-12-13 19:39 UTC by Yevhenko

2019-12-15 18:52 UTC, VitaliiHurin requested changes
Присутні файли з попередніх домашок.

2019-12-15 19:44 UTC, VitaliiHurin requested changes

2019-12-15 19:44 UTC, VitaliiHurin commented on homework-05/src/index.js
> +let url = require('url');
Чому тут let?

2019-12-15 19:44 UTC, VitaliiHurin commented on homework-05/src/index.js
> +  url = new URL(originalUrl);
Тепер ясно чому там let. :) Потрібно переробити, щоб не перетинались назви.

2019-12-15 19:44 UTC, VitaliiHurin commented on homework-05/src/index.js
> +    return err;
Тут не годиться повертати назовні err через return.

2019-12-15 19:44 UTC, VitaliiHurin commented on homework-05/src/index.js
> +    return err;
Тут не годиться повертати назовні err через return.

2019-12-15 19:44 UTC, VitaliiHurin commented on homework-05/src/index.js
> +    const object = await getObjectFromFile(file);
Всі await'и краще обгортати в try/catch.

2019-12-16 12:04 UTC, Yevhenko commented on homework-05/src/index.js
> +    const object = await getObjectFromFile(file);
все переробив

2019-12-21 18:53 UTC, VitaliiHurin approved these changes

2019-12-27 21:41 UTC, RPVanarx approved these changes

2019-12-27 22:21 UTC, merged